### ISSUE TITLE
M.2 finger problem

### ISSUE THREAD

**Issue by imzyxwvu** [ryankurte/altium-library#1]
It seems the bottom layer fingers of M.2 card are not at the same position as those on the top layer. But in the PcbLib file provided (https://github.com/ryankurte/altium-library/blob/master/footprints/m2.PcbLib), the fingers are overlapping. Is this compatible with the general M.2 socket?

https://www.amphenol-icc.com/media/wysiwyg/files/drawing/10130618.pdf

**Comment by ryankurte** [comment]
Wow good catch, I haven't had a chance to fab anything m.2 yet but it seems like a mistake to me!

**Comment by ryankurte** [comment]
i've now fabbed and tested the m.2 e and while i could only test by hand which isn't perfect i believe they're correct now.

![image](https://user-images.githubusercontent.com/860620/160303514-2f32b2ba-2bf9-4063-b253-423cdf0b6503.png)

thanks for the report, i hope you are/were successful in your m.2 adventures!
